package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"goperfcheck/checker"
)

// checkerCategory maps internal checker names to human-readable section titles.
var checkerCategory = map[string]string{
	"MemPrealloc":     "Memory Preallocation",
	"ObjectPool":      "Object Pooling",
	"StructAlign":     "Struct Field Alignment",
	"InterfaceBoxing": "Interface Boxing",
	"ZeroCopy":        "Zero-Copy I/O",
	"GoroutinePool":   "Goroutine Pools",
	"ContextMisuse":   "Context Misuse",
	"BufferedIO":      "Buffered I/O",
	"AtomicMutex":     "Atomic vs Mutex",
	"LazyInit":        "Lazy Initialization",
	"StackAlloc":      "Stack Allocation",
	"Batching":        "Batching Operations",
}

func issueEmoji(s checker.Severity) string {
	switch s {
	case checker.SeverityError:
		return "🔴"
	case checker.SeverityWarning:
		return "🟡"
	default:
		return "🔵"
	}
}

func writeMarkdownReport(path string, issues []checker.Issue, dir string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	absDir, _ := filepath.Abs(dir)

	fmt.Fprintf(f, "# goperfcheck Performance Report\n\n")
	fmt.Fprintf(f, "| | |\n|---|---|\n")
	fmt.Fprintf(f, "| **Directory** | `%s` |\n", absDir)
	fmt.Fprintf(f, "| **Date** | %s |\n", time.Now().Format("2006-01-02"))
	fmt.Fprintf(f, "| **Total issues** | %d |\n\n", len(issues))

	if len(issues) == 0 {
		fmt.Fprintf(f, "✅ No performance issues found.\n")
		return nil
	}

	// ── Summary table ──────────────────────────────────────────────────────────
	// Group issues by checker, preserving the canonical checker order.
	type categorySummary struct {
		name    string
		title   string
		errors  int
		warns   int
		infos   int
		issues  []checker.Issue
	}

	byChecker := make(map[string]*categorySummary)
	// Preserve the order in which checkers first appear (already sorted by
	// file+line, so the first occurrence gives a stable ordering).
	var order []string
	for _, iss := range issues {
		if _, seen := byChecker[iss.Checker]; !seen {
			title := checkerCategory[iss.Checker]
			if title == "" {
				title = iss.Checker
			}
			byChecker[iss.Checker] = &categorySummary{name: iss.Checker, title: title}
			order = append(order, iss.Checker)
		}
		cs := byChecker[iss.Checker]
		switch iss.Severity {
		case checker.SeverityError:
			cs.errors++
		case checker.SeverityWarning:
			cs.warns++
		default:
			cs.infos++
		}
		cs.issues = append(cs.issues, iss)
	}
	// Sort categories alphabetically by title for a consistent report.
	sort.Slice(order, func(i, j int) bool {
		return byChecker[order[i]].title < byChecker[order[j]].title
	})

	fmt.Fprintf(f, "## Summary\n\n")
	fmt.Fprintf(f, "| Category | 🔴 Error | 🟡 Warning | 🔵 Info | Total |\n")
	fmt.Fprintf(f, "|----------|:--------:|:---------:|:------:|:-----:|\n")
	for _, name := range order {
		cs := byChecker[name]
		total := cs.errors + cs.warns + cs.infos
		fmt.Fprintf(f, "| [%s](#%s) | %d | %d | %d | **%d** |\n",
			cs.title, mdAnchor(cs.title), cs.errors, cs.warns, cs.infos, total)
	}
	fmt.Fprintf(f, "\n---\n\n")

	// ── Per-category detail sections ──────────────────────────────────────────
	for _, name := range order {
		cs := byChecker[name]

		fmt.Fprintf(f, "## %s\n\n", cs.title)

		// Severity badge line
		var badges []string
		if cs.errors > 0 {
			badges = append(badges, fmt.Sprintf("🔴 **%d error(s)**", cs.errors))
		}
		if cs.warns > 0 {
			badges = append(badges, fmt.Sprintf("🟡 **%d warning(s)**", cs.warns))
		}
		if cs.infos > 0 {
			badges = append(badges, fmt.Sprintf("🔵 **%d info(s)**", cs.infos))
		}
		fmt.Fprintf(f, "%s\n\n", strings.Join(badges, " · "))

		// Rule link (from the first issue that has one)
		for _, iss := range cs.issues {
			if iss.Rule != "" {
				fmt.Fprintf(f, "> %s\n\n", iss.Rule)
				break
			}
		}

		// One block per issue
		for _, iss := range cs.issues {
			rel, _ := filepath.Rel(dir, iss.File)
			if rel == "" {
				rel = iss.File
			}
			fmt.Fprintf(f, "**`%s:%d`** %s `[%s]`  \n", rel, iss.Line, issueEmoji(iss.Severity), iss.Severity)
			fmt.Fprintf(f, "⚠ %s  \n", iss.Message)
			if iss.Suggestion != "" {
				fmt.Fprintf(f, "💡 %s\n", iss.Suggestion)
			}
			fmt.Fprintf(f, "\n")
		}

		fmt.Fprintf(f, "---\n\n")
	}

	fmt.Fprintf(f, "*Generated by [goperfcheck](https://goperf.dev)*\n")
	return nil
}

// mdAnchor converts a section title to the GitHub Markdown anchor format.
func mdAnchor(title string) string {
	s := strings.ToLower(title)
	s = strings.ReplaceAll(s, " ", "-")
	s = strings.ReplaceAll(s, "/", "")
	return s
}
