package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/haribabuk113/goperfcheck/checker"
)

// checkerCategory maps internal checker names to human-readable section titles.
var checkerCategory = map[string]string{
	"MemPrealloc":     "Memory Preallocation",
	"ObjectPool":      "Object Pooling",
	"StructAlign":     "Struct Field Alignment",
	"InterfaceBoxing": "Interface Boxing",
	"ZeroCopy":        "Zero-Copy I/O",
	"GoroutinePool":   "Goroutine Pools",
	"ContextMisuse":   "Context Misuse",
	"BufferedIO":      "Buffered I/O",
	"AtomicMutex":     "Atomic vs Mutex",
	"LazyInit":        "Lazy Initialization",
	"StackAlloc":      "Stack Allocation",
	"Batching":        "Batching Operations",
	"TimeNowLoop":     "time.Now() in Loops",
	"WaitGroupMisuse": "WaitGroup Misuse",
}

// ew is a write-error accumulator: the first Fprintf error is stored and all
// subsequent writes are skipped, so callers only need to check err once at the end.
type ew struct {
	w   *bufio.Writer
	err error
}

func (e *ew) printf(format string, args ...any) {
	if e.err != nil {
		return
	}
	_, e.err = fmt.Fprintf(e.w, format, args...)
}

func issueEmoji(s checker.Severity) string {
	switch s {
	case checker.SeverityError:
		return "🔴"
	case checker.SeverityWarning:
		return "🟡"
	default:
		return "🔵"
	}
}

func writeMarkdownReport(path string, issues []checker.Issue, dir string) (retErr error) {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer func() {
		if cerr := f.Close(); cerr != nil && retErr == nil {
			retErr = cerr
		}
	}()

	w := &ew{w: bufio.NewWriter(f)}
	absDir, _ := filepath.Abs(dir)

	w.printf("# goperfcheck Performance Report\n\n")
	w.printf("| | |\n|---|---|\n")
	w.printf("| **Directory** | `%s` |\n", absDir)
	w.printf("| **Date** | %s |\n", time.Now().Format("2006-01-02"))
	w.printf("| **Total issues** | %d |\n\n", len(issues))

	if len(issues) == 0 {
		w.printf("✅ No performance issues found.\n")
		if w.err != nil {
			return w.err
		}
		return w.w.Flush()
	}

	// ── Summary table ──────────────────────────────────────────────────────────
	type categorySummary struct {
		name   string
		title  string
		errors int
		warns  int
		infos  int
		issues []checker.Issue
	}

	byChecker := make(map[string]*categorySummary)
	var order []string
	for _, iss := range issues {
		if _, seen := byChecker[iss.Checker]; !seen {
			title := checkerCategory[iss.Checker]
			if title == "" {
				title = iss.Checker
			}
			byChecker[iss.Checker] = &categorySummary{name: iss.Checker, title: title}
			order = append(order, iss.Checker)
		}
		cs := byChecker[iss.Checker]
		switch iss.Severity {
		case checker.SeverityError:
			cs.errors++
		case checker.SeverityWarning:
			cs.warns++
		default:
			cs.infos++
		}
		cs.issues = append(cs.issues, iss)
	}
	sort.Slice(order, func(i, j int) bool {
		return byChecker[order[i]].title < byChecker[order[j]].title
	})

	w.printf("## Summary\n\n")
	w.printf("| Category | 🔴 Error | 🟡 Warning | 🔵 Info | Total |\n")
	w.printf("|----------|:--------:|:---------:|:------:|:-----:|\n")
	for _, name := range order {
		cs := byChecker[name]
		total := cs.errors + cs.warns + cs.infos
		w.printf("| [%s](#%s) | %d | %d | %d | **%d** |\n",
			cs.title, mdAnchor(cs.title), cs.errors, cs.warns, cs.infos, total)
	}
	w.printf("\n---\n\n")

	// ── Per-category detail sections ──────────────────────────────────────────
	for _, name := range order {
		cs := byChecker[name]

		w.printf("## %s\n\n", cs.title)

		var badges []string
		if cs.errors > 0 {
			badges = append(badges, fmt.Sprintf("🔴 **%d error(s)**", cs.errors))
		}
		if cs.warns > 0 {
			badges = append(badges, fmt.Sprintf("🟡 **%d warning(s)**", cs.warns))
		}
		if cs.infos > 0 {
			badges = append(badges, fmt.Sprintf("🔵 **%d info(s)**", cs.infos))
		}
		w.printf("%s\n\n", strings.Join(badges, " · "))

		for _, iss := range cs.issues {
			if iss.Rule != "" {
				w.printf("> %s\n\n", iss.Rule)
				break
			}
		}

		for _, iss := range cs.issues {
			rel, _ := filepath.Rel(absDir, iss.File)
			if rel == "" {
				rel = iss.File
			}
			w.printf("**`%s:%d`** %s `[%s]`  \n", rel, iss.Line, issueEmoji(iss.Severity), iss.Severity)
			w.printf("⚠ %s  \n", iss.Message)
			if iss.Suggestion != "" {
				w.printf("💡 %s  \n", iss.Suggestion)
			}
			if iss.Benchmark != "" {
				w.printf("📊 %s\n", iss.Benchmark)
			}
			w.printf("\n")
		}

		w.printf("---\n\n")
	}

	w.printf("*Generated by [goperfcheck](https://goperf.dev)*\n")

	if w.err != nil {
		return w.err
	}
	return w.w.Flush()
}

// mdAnchor converts a section title to the GitHub Markdown anchor format.
func mdAnchor(title string) string {
	s := strings.ToLower(title)
	s = strings.ReplaceAll(s, " ", "-")
	s = strings.ReplaceAll(s, "/", "")
	return s
}
